// <auto-generated />
using System;
using FactoryWatch.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FactoryWatch.Api.Data.Migrations
{
    [DbContext(typeof(FactoryWatchContext))]
    [Migration("20251105042506_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("FactoryWatch.Api.Entities.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("LastMaintenanceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("NextMaintenanceDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EquipmentList");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 5, 4, 25, 6, 379, DateTimeKind.Utc).AddTicks(4118),
                            Description = "Main conveyor belt for assembly line",
                            LastMaintenanceDate = new DateOnly(2024, 10, 15),
                            Location = "Assembly Line 1",
                            Name = "Conveyor Belt A1",
                            NextMaintenanceDate = new DateOnly(2024, 12, 15),
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 11, 5, 4, 25, 6, 379, DateTimeKind.Utc).AddTicks(4174)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 5, 4, 25, 6, 379, DateTimeKind.Utc).AddTicks(4232),
                            Description = "Heavy-duty hydraulic press",
                            LastMaintenanceDate = new DateOnly(2024, 11, 1),
                            Location = "Station 5",
                            Name = "Hydraulic Press B2",
                            NextMaintenanceDate = new DateOnly(2025, 1, 1),
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 11, 5, 4, 25, 6, 379, DateTimeKind.Utc).AddTicks(4232)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 5, 4, 25, 6, 379, DateTimeKind.Utc).AddTicks(4234),
                            Description = "6-axis robotic arm for precision assembly",
                            LastMaintenanceDate = new DateOnly(2024, 9, 20),
                            Location = "Assembly Line 2",
                            Name = "Robotic Arm C3",
                            NextMaintenanceDate = new DateOnly(2024, 11, 20),
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 11, 5, 4, 25, 6, 379, DateTimeKind.Utc).AddTicks(4234)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
